version: "3.8"
name: ServerControl
services:

  #
  #    EXAMPLE SETUP
  #

  application:
    image: ghcr.io/flamestro/example-application:main
    pull_policy: always
    expose:
     - 8080
    networks:
      service_network:
    cpus: 0.6
    mem_reservation: "200M"
    mem_limit: "600M"
    environment:
      ENV_VAR_ONE: ${ENVIRONMENT_VARIABLE_ONE}
      ENV_VAR_TWO: ${ENVIRONMENT_VARIABLE_TWO}
      ENV_VAR_THREE: ${ENVIRONMENT_VARIABLE_THREE}
      HTTP_PORT: 8080
      VIRTUAL_HOST: your.domain.com
      LETSENCRYPT_HOST: your.domain.com
      LETSENCRYPT_EMAIL: "your@domain.com"

  #
  #     SSL SETUP
  #

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    container_name: nginx-proxy
    networks:
      service_network:
    cpus: 0.5
    mem_reservation: "10M"
    mem_limit: "500M"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      NGINX_PROXY_CONTAINER: "nginx-proxy"
    networks:
      service_network:
    cpus: 0.1
    mem_reservation: "10M"
    mem_limit: "100M"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html

networks:
  service_network:

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  minecraft-server: {}
